-- FINAL AI FIX V13: Single Global API Key Architecture
-- Enforces ONE OpenRouter Key for ALL models.
-- Removes per-model key storage.

BEGIN;

-- 1. Enable Encryption
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- 2. Create Global Provider Settings Table
CREATE TABLE IF NOT EXISTS public.ai_provider_settings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_name text NOT NULL UNIQUE DEFAULT 'openrouter',
    api_key_encrypted text NOT NULL,
    is_active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Create Clean AI Models Table (NO API KEY COLUMN)
DROP TABLE IF EXISTS public.ai_models CASCADE; -- Force clean slate to ensure schema match
CREATE TABLE public.ai_models (
    id text PRIMARY KEY, -- check constraints will send exact IDs like 'openai/gpt-4'
    model_name text NOT NULL,
    display_name text NOT NULL,
    group_name text NOT NULL, -- 'text', 'image', 'voice', 'code'
    enabled boolean DEFAULT true,
    is_default_main boolean DEFAULT false,
    is_default_student boolean DEFAULT false,
    provider text DEFAULT 'openrouter',
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Secure RPC: Save Global Key
-- Hardcoded secret for now as requested/used in previous iterations for simplicity in this context.
-- In a real production env, we'd use Vault, but sticking to the user's pgcrypto pattern.
CREATE OR REPLACE FUNCTION public.save_provider_key(
    p_key text
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_secret text := 'deedox_secure_ai_persistence_key_2026';
BEGIN
    INSERT INTO public.ai_provider_settings (provider_name, api_key_encrypted)
    VALUES ('openrouter', pgp_sym_encrypt(p_key, v_secret))
    ON CONFLICT (provider_name)
    DO UPDATE SET 
        api_key_encrypted = pgp_sym_encrypt(p_key, v_secret),
        updated_at = now();
END;
$$;

-- 5. Secure RPC: Get Decrypted Key (Internal Use Only)
CREATE OR REPLACE FUNCTION public.get_decrypted_provider_key()
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_key text;
    v_secret text := 'deedox_secure_ai_persistence_key_2026';
BEGIN
    SELECT pgp_sym_decrypt(api_key_encrypted::bytea, v_secret) 
    INTO v_key
    FROM public.ai_provider_settings
    WHERE provider_name = 'openrouter';
    
    RETURN v_key;
END;
$$;

-- 6. RPC: Check if Key Exists (For Admin UI Status)
CREATE OR REPLACE FUNCTION public.check_provider_key_status()
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_exists boolean;
BEGIN
    SELECT EXISTS(
        SELECT 1 FROM public.ai_provider_settings 
        WHERE provider_name = 'openrouter' AND is_active = true
    ) INTO v_exists;
    
    RETURN v_exists;
END;
$$;

-- 7. Seed Data: Strictly Valid OpenRouter Models
DELETE FROM public.ai_models;

-- Text / Reasoning
INSERT INTO public.ai_models (id, model_name, display_name, group_name, enabled, is_default_main) VALUES
('openai/gpt-oss-120b', 'openai/gpt-oss-120b', 'GPT-4o (Omni)', 'text', true, true),
('meta-llama/llama-3.1-70b-instruct', 'meta-llama/llama-3.1-70b-instruct', 'Llama 3.1 70B', 'text', true, false),
('deepseek-ai/deepseek-r1', 'deepseek-ai/deepseek-r1', 'DeepSeek R1', 'text', true, false),
('deepseek-ai/deepseek-v3', 'deepseek-ai/deepseek-v3', 'DeepSeek V3', 'text', true, false);

-- Coding
INSERT INTO public.ai_models (id, model_name, display_name, group_name, enabled) VALUES
('qwen/qwen-2.5-coder-32b', 'qwen/qwen-2.5-coder-32b', 'Qwen 2.5 Coder', 'code', true),
('eleutherai/gpt-neox-20b', 'eleutherai/gpt-neox-20b', 'GPT-NeoX 20B', 'code', true);

-- Image Generation
INSERT INTO public.ai_models (id, model_name, display_name, group_name, enabled) VALUES
('stabilityai/stable-diffusion-xl-base-1.0', 'stabilityai/stable-diffusion-xl-base-1.0', 'Stable Diffusion XL', 'image', true),
('stabilityai/stable-diffusion-3', 'stabilityai/stable-diffusion-3', 'Stable Diffusion 3', 'image', true);

-- Voice
INSERT INTO public.ai_models (id, model_name, display_name, group_name, enabled) VALUES
('openai/whisper-large-v3', 'openai/whisper-large-v3', 'Whisper V3', 'voice', true);


-- 8. Enable RLS
ALTER TABLE public.ai_provider_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_models ENABLE ROW LEVEL SECURITY;

-- Policies
DROP POLICY IF EXISTS "Public Read Models" ON public.ai_models;
CREATE POLICY "Public Read Models" ON public.ai_models FOR SELECT USING (true);

DROP POLICY IF EXISTS "Admin Full Access Models" ON public.ai_models;
CREATE POLICY "Admin Full Access Models" ON public.ai_models FOR ALL USING (auth.role() = 'authenticated'); -- Assuming Admin is authenticated

DROP POLICY IF EXISTS "Admin Full Access Settings" ON public.ai_provider_settings;
CREATE POLICY "Admin Full Access Settings" ON public.ai_provider_settings FOR ALL USING (auth.role() = 'authenticated');

COMMIT;
