-- FIX: Secure API Key Storage (V11)
-- Enables pgcrypto, creates storage table, and admin-only secure functions.

BEGIN;

-- 1. Enable Encryption Extension
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- 2. Create Keys Table
CREATE TABLE IF NOT EXISTS public.ai_api_keys (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider text NOT NULL UNIQUE, -- 'openrouter', 'openai', etc.
    api_key_encrypted text NOT NULL, -- Encrypted string
    is_active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Enable RLS
ALTER TABLE public.ai_api_keys ENABLE ROW LEVEL SECURITY;

-- 4. Policies (Strict)
-- Only Service Role should ideally access this, but for Admin Panel usage we might allow Authenticated users with specific role.
-- For now: Allow access to 'authenticated' users (assuming Admin is authenticated).
DROP POLICY IF EXISTS "Admin Access Keys" ON public.ai_api_keys;
CREATE POLICY "Admin Access Keys" ON public.ai_api_keys
    FOR ALL
    USING (auth.role() = 'authenticated');

-- 5. Secure Function to Save Key (Encrypts on Server-Side DB)
CREATE OR REPLACE FUNCTION public.save_api_key(
    p_provider text,
    p_key text,
    p_secret text -- The encryption secret (Env var passed from server)
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER -- Runs with elevated privileges
AS $$
BEGIN
    INSERT INTO public.ai_api_keys (provider, api_key_encrypted)
    VALUES (p_provider, pgp_sym_encrypt(p_key, p_secret))
    ON CONFLICT (provider)
    DO UPDATE SET 
        api_key_encrypted = pgp_sym_encrypt(p_key, p_secret),
        updated_at = now();
END;
$$;

-- 6. Secure Function to Get Key (Decrypts for Usage)
-- NOTE: This returns the RAW key. It should ONLY be called by the Server/Proxy.
CREATE OR REPLACE FUNCTION public.get_decrypted_key(
    p_provider text,
    p_secret text
)
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_key text;
BEGIN
    SELECT pgp_sym_decrypt(api_key_encrypted::bytea, p_secret) 
    INTO v_key
    FROM public.ai_api_keys
    WHERE provider = p_provider;
    
    RETURN v_key;
END;
$$;

COMMIT;
