-- UPGRADE HERO & SLIDES V9
-- Defines dedicated tables for Hero Backgrounds and Slide Cards with advanced styling controls.

BEGIN;

-- 1. Create Hero Images Table
CREATE TABLE IF NOT EXISTS public.hero_images (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_url text NOT NULL,
    alt_text text DEFAULT 'Hero Background',
    enabled boolean DEFAULT true,
    blur_level integer DEFAULT 0, -- 0 to 20 (px)
    opacity_level integer DEFAULT 50, -- 0 to 100 (%)
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create Slide Card Images Table
CREATE TABLE IF NOT EXISTS public.slide_card_images (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_url text NOT NULL,
    title text DEFAULT '',
    link text DEFAULT '#',
    enabled boolean DEFAULT true,
    blur_level integer DEFAULT 0,
    opacity_level integer DEFAULT 100,
    display_order integer DEFAULT 0,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Enable Rules (RLS)
ALTER TABLE public.hero_images ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.slide_card_images ENABLE ROW LEVEL SECURITY;

-- 4. Policies (Public Read, Admin Write)
DROP POLICY IF EXISTS "Public Read Hero" ON public.hero_images;
CREATE POLICY "Public Read Hero" ON public.hero_images FOR SELECT USING (true);

DROP POLICY IF EXISTS "Admin Write Hero" ON public.hero_images;
CREATE POLICY "Admin Write Hero" ON public.hero_images FOR ALL USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Public Read Slides" ON public.slide_card_images;
CREATE POLICY "Public Read Slides" ON public.slide_card_images FOR SELECT USING (true);

DROP POLICY IF EXISTS "Admin Write Slides" ON public.slide_card_images;
CREATE POLICY "Admin Write Slides" ON public.slide_card_images FOR ALL USING (auth.role() = 'authenticated');

-- 5. Seed Initial Data (So the site isn't empty)
INSERT INTO public.hero_images (image_url, opacity_level, blur_level) VALUES 
('https://images.unsplash.com/photo-1620712943543-bcc4688e7485?q=80&w=1965&auto=format&fit=crop', 50, 0);

INSERT INTO public.slide_card_images (image_url, title, display_order) VALUES 
('https://placehold.co/480x280/1e2139/FFFFFF/png?text=Program', 'Programs in Action', 1),
('https://placehold.co/480x280/1e2139/FFFFFF/png?text=Community', 'Community Event', 2),
('https://placehold.co/480x280/1e2139/FFFFFF/png?text=Workshop', 'AI Workshop', 3);

COMMIT;
