-- FIX PERSISTENCE V10
-- Strict database-driven content for Hero, Slider, and Socials.
-- Migrates from JSON site_settings to dedicated tables.

BEGIN;

-- 1. HERO SECTION (Single Row Configuration)
CREATE TABLE IF NOT EXISTS public.homepage_hero (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text DEFAULT 'Asia’s First', -- General title
    title_prefix text DEFAULT 'Asia’s First', -- For top line
    title_highlight text DEFAULT 'AI Startup Institute', -- For green highlight
    subtitle text DEFAULT 'AI Startup Institute', -- Legacy
    description text DEFAULT 'Learn how to use AI to build the next big thing.',
    background_image_url text DEFAULT '',
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. SLIDER CARDS (Multiple Rows)
CREATE TABLE IF NOT EXISTS public.homepage_slider_cards (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text DEFAULT 'New Card',
    description text DEFAULT '',
    image_url text NOT NULL,
    redirect_link text DEFAULT '#',
    enabled boolean DEFAULT true,
    display_order integer DEFAULT 0,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. SOCIAL & CONTACT (Single Row)
CREATE TABLE IF NOT EXISTS public.website_contact_social (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email text DEFAULT 'hello@deedox.ai',
    phone text DEFAULT '+1 234 567 890',
    address text DEFAULT '123 Innovation Drive, Tech City',
    facebook_url text DEFAULT '#',
    instagram_url text DEFAULT '#',
    twitter_url text DEFAULT '#',
    linkedin_url text DEFAULT '#',
    whatsapp_url text DEFAULT '923001234567',
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. ENABLE RLS
ALTER TABLE public.homepage_hero ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.homepage_slider_cards ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.website_contact_social ENABLE ROW LEVEL SECURITY;

-- 5. ACCESS POLICIES (Public Read, Admin Write)
-- Hero
DROP POLICY IF EXISTS "Public Read Hero" ON public.homepage_hero;
CREATE POLICY "Public Read Hero" ON public.homepage_hero FOR SELECT USING (true);
DROP POLICY IF EXISTS "Admin Write Hero" ON public.homepage_hero;
CREATE POLICY "Admin Write Hero" ON public.homepage_hero FOR ALL USING (auth.role() = 'authenticated');

-- Sliders
DROP POLICY IF EXISTS "Public Read Sliders" ON public.homepage_slider_cards;
CREATE POLICY "Public Read Sliders" ON public.homepage_slider_cards FOR SELECT USING (true);
DROP POLICY IF EXISTS "Admin Write Sliders" ON public.homepage_slider_cards;
CREATE POLICY "Admin Write Sliders" ON public.homepage_slider_cards FOR ALL USING (auth.role() = 'authenticated');

-- Socials
DROP POLICY IF EXISTS "Public Read Socials" ON public.website_contact_social;
CREATE POLICY "Public Read Socials" ON public.website_contact_social FOR SELECT USING (true);
DROP POLICY IF EXISTS "Admin Write Socials" ON public.website_contact_social;
CREATE POLICY "Admin Write Socials" ON public.website_contact_social FOR ALL USING (auth.role() = 'authenticated');

-- 6. SEED INITIAL DATA (If Empty)
INSERT INTO public.homepage_hero (title, subtitle, description, background_image_url)
SELECT 'Asia''s First', 'AI Startup Institute', 'Learn how to use AI to build the next big thing.', 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?q=80&w=1965&auto=format&fit=crop'
WHERE NOT EXISTS (SELECT 1 FROM public.homepage_hero);

INSERT INTO public.website_contact_social (email, phone, address, facebook_url)
SELECT 'hello@deedox.ai', '+880 1234 567890', 'Dhaka, Bangladesh', 'https://facebook.com/deedox'
WHERE NOT EXISTS (SELECT 1 FROM public.website_contact_social);

-- Seed defaults for Slider Cards if empty
INSERT INTO public.homepage_slider_cards (title, description, image_url, redirect_link, display_order)
SELECT 'Programs in Action', 'Check out our latest workshops.', 'https://placehold.co/480x280/1e2139/FFFFFF/png?text=Program', '/programs', 1
WHERE NOT EXISTS (SELECT 1 FROM public.homepage_slider_cards);

COMMIT;
