BEGIN;

-- MASTER AI SYSTEM RESET (V16)
-- Fully stable, admin-controlled, single-key architecture.
-- Replaces previous AI settings tables.

-- 1. AI SYSTEM SETTINGS (Single Row, Single Key)
-------------------------------------------------
DROP TABLE IF EXISTS public.ai_system_settings CASCADE;
CREATE TABLE public.ai_system_settings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_name text NOT NULL UNIQUE DEFAULT 'openrouter',
    api_key_encrypted text NOT NULL,
    is_active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.ai_system_settings ENABLE ROW LEVEL SECURITY;

-- 2. AI MODELS REGISTRY (Fixed List, Toggleable)
-------------------------------------------------
DROP TABLE IF EXISTS public.ai_models CASCADE;
CREATE TABLE public.ai_models (
    id text PRIMARY KEY, -- 'deepseek/deepseek-r1'
    model_id text NOT NULL, -- same as id, redundant but explicit for queries
    display_name text NOT NULL,
    group_type text NOT NULL, -- 'text', 'image', 'voice', 'code'
    enabled boolean DEFAULT true,
    is_default boolean DEFAULT false,
    order_index integer DEFAULT 0,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.ai_models ENABLE ROW LEVEL SECURITY;

-- 3. SEED MODELS (Mandatory List)
----------------------------------
INSERT INTO public.ai_models (id, model_id, display_name, group_type, enabled, is_default, order_index) VALUES
-- TEXT
('deepseek-ai/deepseek-r1', 'deepseek-ai/deepseek-r1', 'DeepSeek R1', 'text', true, true, 1),
('deepseek-ai/deepseek-v3', 'deepseek-ai/deepseek-v3', 'DeepSeek V3', 'text', true, false, 2),
('meta-llama/llama-3.1-70b-instruct', 'meta-llama/llama-3.1-70b-instruct', 'Llama 3.1 70B', 'text', true, false, 3),
('openai/gpt-4o', 'openai/gpt-4o', 'GPT-4o (Omni)', 'text', true, false, 4), 
('eleutherai/gpt-neox-20b', 'eleutherai/gpt-neox-20b', 'GPT-NeoX 20B', 'text', true, false, 5),
('tinyllama/tinyllama-1.1b-chat', 'tinyllama/tinyllama-1.1b-chat', 'TinyLlama 1.1B', 'text', true, false, 6),
-- IMAGE
('stabilityai/stable-diffusion-xl-base-1.0', 'stabilityai/stable-diffusion-xl-base-1.0', 'Stable Diffusion XL', 'image', true, true, 1),
('stabilityai/stable-diffusion-3-medium', 'stabilityai/stable-diffusion-3-medium', 'Stable Diffusion 3', 'image', true, false, 2),
-- VOICE
('openai/whisper-large-v3', 'openai/whisper-large-v3', 'Whisper V3', 'voice', true, true, 1),
-- CODE
('qwen/qwen-2.5-coder-32b-instruct', 'qwen/qwen-2.5-coder-32b-instruct', 'Qwen 2.5 Coder', 'code', true, true, 1)
ON CONFLICT (id) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    group_type = EXCLUDED.group_type;


-- 4. SECURE RPC: SAVE SETTINGS (Strict Update Logic)
-----------------------------------------------------
CREATE OR REPLACE FUNCTION public.save_ai_system_settings(
    p_key text
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_secret text := 'deedox_secure_ai_persistence_key_2026';
BEGIN
    -- Only update if key is valid (not empty, not masked)
    IF p_key IS NOT NULL AND p_key != '' AND p_key NOT LIKE '%*%' THEN
        INSERT INTO public.ai_system_settings (provider_name, api_key_encrypted)
        VALUES ('openrouter', pgp_sym_encrypt(p_key, v_secret))
        ON CONFLICT (provider_name)
        DO UPDATE SET 
            api_key_encrypted = pgp_sym_encrypt(p_key, v_secret),
            updated_at = now();
    ELSE
        -- If invalid, ensure record exists but DO NOT touch key
        INSERT INTO public.ai_system_settings (provider_name, api_key_encrypted)
        VALUES ('openrouter', pgp_sym_encrypt('PLACEHOLDER_KEY', v_secret))
        ON CONFLICT (provider_name) DO NOTHING;
        
        RAISE NOTICE 'Skipping Key Update: Invalid input provided.';
    END IF;
END;
$$;

-- 5. SECURE RPC: GET MASKED KEY (For UI)
-----------------------------------------
CREATE OR REPLACE FUNCTION public.get_ai_system_settings_masked()
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_key text;
    v_secret text := 'deedox_secure_ai_persistence_key_2026';
    v_decrypted text;
BEGIN
    SELECT pgp_sym_decrypt(api_key_encrypted::bytea, v_secret) 
    INTO v_decrypted
    FROM public.ai_system_settings
    WHERE provider_name = 'openrouter';
    
    IF v_decrypted IS NOT NULL AND length(v_decrypted) > 10 THEN
        RETURN substr(v_decrypted, 1, 10) || '................' || substr(v_decrypted, length(v_decrypted) - 4, 5);
    ELSE
        RETURN NULL;
    END IF;
END;
$$;

-- 6. SECURE RPC: GET DECRYPTED KEY (For Backend Only)
------------------------------------------------------
CREATE OR REPLACE FUNCTION public.get_decrypted_system_key()
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_key text;
    v_secret text := 'deedox_secure_ai_persistence_key_2026';
BEGIN
    SELECT pgp_sym_decrypt(api_key_encrypted::bytea, v_secret) 
    INTO v_key
    FROM public.ai_system_settings
    WHERE provider_name = 'openrouter';
    
    RETURN v_key;
END;
$$;

-- 7. MODEL MANAGEMENT RPCs
---------------------------
CREATE OR REPLACE FUNCTION public.toggle_model_enabled(
    p_model_id text,
    p_enabled boolean
)
RETURNS void
LANGUAGE sql
SECURITY DEFINER
AS $$
    UPDATE public.ai_models
    SET enabled = p_enabled, updated_at = now()
    WHERE id = p_model_id;
$$;

CREATE OR REPLACE FUNCTION public.set_model_default(
    p_model_id text,
    p_group_type text
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    -- Reset all in group
    UPDATE public.ai_models
    SET is_default = false
    WHERE group_type = p_group_type;
    
    -- Set new default
    UPDATE public.ai_models
    SET is_default = true
    WHERE id = p_model_id;
END;
$$;


-- 8. PERMISSIONS & POLICIES
----------------------------
GRANT EXECUTE ON FUNCTION public.save_ai_system_settings(text) TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.get_ai_system_settings_masked() TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.toggle_model_enabled(text, boolean) TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.set_model_default(text, text) TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.get_decrypted_system_key() TO service_role;

-- Allow public read of enabled models (for frontend display)
DROP POLICY IF EXISTS "Public Read Models" ON public.ai_models;
CREATE POLICY "Public Read Models" ON public.ai_models FOR SELECT USING (true);

-- Allow admin write access (authenticated)
DROP POLICY IF EXISTS "Admin Write Models" ON public.ai_models;
CREATE POLICY "Admin Write Models" ON public.ai_models FOR ALL USING (auth.role() = 'authenticated');

-- Allow system settings read (masked via RPC ideally, but allow select for authenticated)
DROP POLICY IF EXISTS "Admin Settings" ON public.ai_system_settings;
CREATE POLICY "Admin Settings" ON public.ai_system_settings FOR ALL USING (true); -- RPC handles security, this is fallback

COMMIT;
